"""Static domain catalogs: acute red-flag keywords and the exercise library."""

from __future__ import annotations

from typing import Any

RED_FLAG_KEYWORDS = (
    "严重胸痛",
    "胸痛",
    "严重胸闷",
    "胸闷",
    "呼吸困难",
    "晕厥",
    "眩晕",
    "黑朦",
    "撕裂样剧痛",
    "急性剧烈关节刺痛",
    "chest pain",
    "syncope",
    "dyspnea",
)

EXERCISE_CATALOG: dict[str, dict[str, Any]] = {
    # Lower Body - Squat (knee dominant)
    "Barbell Back Squat": {
        "name": "Barbell Back Squat",
        "movement_pattern": "lower_squat",
        "equipment": {"barbell"},
        "contraindications": {"knee", "lumbar"},
        "tiers": {"standard"},
        "default_sets": 3,
        "reps_min": 6,
        "reps_max": 8,
        "rest_seconds": 150,
    },
    "Dumbbell Goblet Squat": {
        "name": "Dumbbell Goblet Squat",
        "movement_pattern": "lower_squat",
        "equipment": {"dumbbell"},
        "contraindications": {"knee"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 90,
    },
    "Bodyweight Squat": {
        "name": "Bodyweight Squat",
        "movement_pattern": "lower_squat",
        "equipment": {"bodyweight"},
        "contraindications": {"knee"},
        "tiers": {"standard", "recovery", "deload"},
        "default_sets": 2,
        "reps_min": 10,
        "reps_max": 15,
        "rest_seconds": 60,
    },
    # Lower Body - Hinge / Glute (knee friendly)
    "Barbell Hip Thrust": {
        "name": "Barbell Hip Thrust",
        "movement_pattern": "lower_hinge",
        "equipment": {"barbell"},
        "contraindications": set(),
        "tiers": {"standard"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 120,
    },
    "Romanian Deadlift": {
        "name": "Romanian Deadlift",
        "movement_pattern": "lower_hinge",
        "equipment": {"barbell"},
        "contraindications": {"lumbar"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 120,
    },
    "Dumbbell Hip Thrust": {
        "name": "Dumbbell Hip Thrust",
        "movement_pattern": "lower_hinge",
        "equipment": {"dumbbell"},
        "contraindications": set(),
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 10,
        "reps_max": 12,
        "rest_seconds": 90,
    },
    "Dumbbell Romanian Deadlift": {
        "name": "Dumbbell Romanian Deadlift",
        "movement_pattern": "lower_hinge",
        "equipment": {"dumbbell"},
        "contraindications": {"lumbar"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 12,
        "rest_seconds": 90,
    },
    "Glute Bridge": {
        "name": "Glute Bridge",
        "movement_pattern": "lower_hinge",
        "equipment": {"bodyweight"},
        "contraindications": set(),
        "tiers": {"standard", "recovery", "deload"},
        "default_sets": 2,
        "reps_min": 12,
        "reps_max": 15,
        "rest_seconds": 60,
    },
    # Upper Body - Push
    "Barbell Bench Press": {
        "name": "Barbell Bench Press",
        "movement_pattern": "upper_push",
        "equipment": {"barbell"},
        "contraindications": {"shoulder"},
        "tiers": {"standard"},
        "default_sets": 3,
        "reps_min": 6,
        "reps_max": 8,
        "rest_seconds": 120,
    },
    "Dumbbell Floor Press": {
        "name": "Dumbbell Floor Press",
        "movement_pattern": "upper_push",
        "equipment": {"dumbbell"},
        "contraindications": {"shoulder"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 90,
    },
    "Pushup": {
        "name": "Pushup",
        "movement_pattern": "upper_push",
        "equipment": {"bodyweight"},
        "contraindications": {"shoulder"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 12,
        "rest_seconds": 60,
    },
    "Incline Pushup": {
        "name": "Incline Pushup",
        "movement_pattern": "upper_push",
        "equipment": {"bodyweight"},
        "contraindications": {"shoulder"},
        "tiers": {"standard", "recovery", "deload"},
        "default_sets": 2,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 60,
    },
    # Upper Body - Pull
    "Barbell Row": {
        "name": "Barbell Row",
        "movement_pattern": "upper_pull",
        "equipment": {"barbell"},
        "contraindications": {"lumbar"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 90,
    },
    "Dumbbell Chest Supported Row": {
        "name": "Dumbbell Chest Supported Row",
        "movement_pattern": "upper_pull",
        "equipment": {"dumbbell"},
        "contraindications": set(),
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 8,
        "reps_max": 10,
        "rest_seconds": 90,
    },
    # Core & Trunk Stability
    "Plank": {
        "name": "Plank",
        "movement_pattern": "core_stability",
        "equipment": {"bodyweight"},
        "contraindications": {"shoulder"},
        "tiers": {"standard", "recovery"},
        "default_sets": 3,
        "reps_min": 30,
        "reps_max": 45,
        "rest_seconds": 60,
    },
    "Bird Dog": {
        "name": "Bird Dog",
        "movement_pattern": "core_stability",
        "equipment": {"bodyweight"},
        "contraindications": set(),
        "tiers": {"standard", "recovery", "deload"},
        "default_sets": 2,
        "reps_min": 10,
        "reps_max": 12,
        "rest_seconds": 60,
    },
    "Dead Bug": {
        "name": "Dead Bug",
        "movement_pattern": "core_stability",
        "equipment": {"bodyweight"},
        "contraindications": set(),
        "tiers": {"standard", "recovery", "deload"},
        "default_sets": 2,
        "reps_min": 10,
        "reps_max": 12,
        "rest_seconds": 60,
    },
}
